version: "3.8"
services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:Oh/GIsnr7gbUJv3WttlYxIGdOlPkbMuPZbNfBaMOr1E=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: your_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
