version: '3.8'
services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_db
            - DB_USERNAME=your_user
            - DB_PASSWORD=your_pass
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: your_db
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_pass
        ports:
            - "3306:3306"
